#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

blockMesh
cp -r 0.orig 0
#runApplication setExprFields
#runApplication $(getApplication)

ccc=$(date '+%Y-%m-%d-%H-%M');
ccc="log_""$ccc";
mybuoyantBoussinesqSimpleFoam > "$ccc" &

#------------------------------------------------------------------------------
